/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ev.esencialgui.gui;

import com.ev.esencialgui.data.*;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Daniel Granados <dagranados@estudiantec.cr>
 */
public class RegistrarVenta extends javax.swing.JFrame {
   private int productoId;
   private String productoNombre;
   private int prodContratoId;
   private int loteId;
   private Producto productoSelected;
   private HashMap<String,Producto> productosMap;
   private HashMap<String, Canal> canalesMap;
   private HashMap<String, Precio> preciosMap;
   private Canal canalSelected;
   private Precio precioSelected;
   private DefaultListModel listaProductosModel;
   private int cantidad;
   private HashMap<String, objetoLista> objetosListaMap; 
   private float montoTotal;
    /**
     * Creates new form registrarVenta
     */
    public RegistrarVenta() {
        initComponents();
        productosMap = new HashMap<>();
        canalesMap = new HashMap<>();
        cantidadText.setInputVerifier(new CantidadInputVerifier());
        listaProductosModel = new DefaultListModel();
        listaProductos.setModel(listaProductosModel);
        listaProductosModel.removeAllElements();
        objetosListaMap = new HashMap<>();
        montoTotal = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            comboProductos = new javax.swing.JComboBox<>();
            jLabel5 = new javax.swing.JLabel();
            cantidadText = new javax.swing.JTextField();
            registrarButton = new javax.swing.JButton();
            cancelarButton = new javax.swing.JButton();
            jLabel6 = new javax.swing.JLabel();
            montoLabel = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jScrollPane2 = new javax.swing.JScrollPane();
            listaProductos = new javax.swing.JList<>();
            addButton = new javax.swing.JButton();
            borrarButton = new javax.swing.JButton();
            jLabel9 = new javax.swing.JLabel();
            comboPrecios = new javax.swing.JComboBox<>();
            jLabel10 = new javax.swing.JLabel();
            cantidadLoteText = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            comboCanales = new javax.swing.JComboBox<>();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            jLabel1.setText("Registrar Venta");
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

            jLabel2.setText("Producto");
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

            comboProductos.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        comboProductosActionPerformed(evt);
                  }
            });
            getContentPane().add(comboProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 230, -1));

            jLabel5.setText("Cantidad");
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

            cantidadText.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cantidadTextActionPerformed(evt);
                  }
            });
            getContentPane().add(cantidadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, -1));

            registrarButton.setText("Registrar Venta");
            getContentPane().add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

            cancelarButton.setText("Cancelar");
            getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

            jLabel6.setText("Monto Total");
            getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

            montoLabel.setText("0");
            getContentPane().add(montoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

            jLabel8.setText("Desglose");
            getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

            jScrollPane2.setViewportView(listaProductos);

            getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, 110));

            addButton.setText("Añadir");
            addButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        addButtonActionPerformed(evt);
                  }
            });
            getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

            borrarButton.setText("Borrar");
            getContentPane().add(borrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

            jLabel9.setText("Precio");
            getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

            comboPrecios.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        comboPreciosActionPerformed(evt);
                  }
            });
            getContentPane().add(comboPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, -1));

            jLabel10.setText("Cantidad disponible: ");
            getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

            cantidadLoteText.setText("0");
            getContentPane().add(cantidadLoteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 60, 20));

            jLabel11.setText("Canal");
            getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, -1));

            comboCanales.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        comboCanalesActionPerformed(evt);
                  }
            });
            getContentPane().add(comboCanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 230, -1));

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        cantidad = -1;
        try {
              cantidad = Integer.valueOf(cantidadLoteText.getText());
        }
        catch (Exception e) {
              return;
        }
        if (canalSelected == null || precioSelected == null || productoSelected == null || cantidad == -1) {
              return;
        }
        String stringLista = productoSelected.getNombre() + " " + cantidad + " " + (cantidad * precioSelected.getPrecioProd());
        objetosListaMap.put(stringLista, new objetoLista(productoSelected, cantidad, (cantidad * precioSelected.getPrecioProd())));
        listaProductosModel.addElement(stringLista);     
        montoTotal += (cantidad * precioSelected.getPrecioProd());
        montoLabel.setText(Float.toString(montoTotal));      
    }//GEN-LAST:event_addButtonActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        // TODO add your handling code here:
        productoSelected = productosMap.get((String) comboProductos.getSelectedItem());
        fillComboPrecios();
    }//GEN-LAST:event_comboProductosActionPerformed

      private void comboCanalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCanalesActionPerformed
            // TODO add your handling code here:
            canalSelected = canalesMap.get((String) comboCanales.getSelectedItem());
      }//GEN-LAST:event_comboCanalesActionPerformed

      private void comboPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPreciosActionPerformed
            // TODO add your handling code here:
            if (productoSelected == null) {
                  return;
            }
            precioSelected = preciosMap.get((String) comboPrecios.getSelectedItem());
            cantidadLoteText.setText(Integer.toString(precioSelected.getCantidadTotal()));
      }//GEN-LAST:event_comboPreciosActionPerformed

      private void cantidadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_cantidadTextActionPerformed

    private void fillComboProductos(){
          comboProductos.removeAllItems();
          productosMap.forEach((key, value) -> {
                comboProductos.addItem(key);
        });
    }  
    
    private void fillComboCanales(){
          comboCanales.removeAllItems();
          canalesMap.forEach((key, value) -> {
                comboCanales.addItem(key);
        });
    }
    
    private void fillComboPrecios(){
          if (productoNombre == null){
                return;
          }
          comboPrecios.removeAllItems();
          preciosMap = new HashMap<>();
          for (Precio precioIter : productoSelected.getPrecios()) {
                comboPrecios.addItem(Float.toString(precioIter.getPrecioProd())+ " dólares");
                preciosMap.put(Float.toString(precioIter.getPrecioProd()), precioIter);
          }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVenta().setVisible(true);
            }
        });
    }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton addButton;
      private javax.swing.JButton borrarButton;
      private javax.swing.JButton cancelarButton;
      private javax.swing.JLabel cantidadLoteText;
      private javax.swing.JTextField cantidadText;
      private javax.swing.JComboBox<String> comboCanales;
      private javax.swing.JComboBox<String> comboPrecios;
      private javax.swing.JComboBox<String> comboProductos;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JList<String> listaProductos;
      private javax.swing.JLabel montoLabel;
      private javax.swing.JButton registrarButton;
      // End of variables declaration//GEN-END:variables
}
